name: Publish 'sageattn-py312' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
    inputs:
      MAX_JOBS:
        description: 'MAX_JOBS to compile'
        required: true
        type: string
        default: "1" # Build slowly but less crash on GitHub CI.

jobs:

  build-images:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'sageattn-py312'
        uses: docker/build-push-action@v6
        with:
          context: ./sageattn-py312
          build-args: |
            MAX_JOBS=${{ inputs.MAX_JOBS }}
          tags:  |
            yanwk/comfyui-extras:sageattn-py312
            yanwk/comfyui-extras:sageattn-py312-${{ steps.date.outputs.date }}
          push: true
